FROM fluent/fluent-bit

COPY fluent-bit.conf /fluent-bit/etc/fluent-bit.conf

COPY custom_parsers.conf /fluent-bit/etc/custom_parsers.conf

CMD ["fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf", "-p", "/fluent-bit/etc/custom_parsers.conf"]
VOLUME /logs
